language: node_js
node_js:
  - "16"
  - "14"
  - "12"
  - "10"

env:
  global:
    - CC_TEST_REPORTER_ID=7754fd23994331dd651be55b7137045414a2ab8a63c05ce6ae78c4ff8c4ad93b

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run test_with_coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
