'use strict';

module.exports = {
    ATOM_MOOV: 'moov',
    ATOM_MVHD: 'mvhd',
    ATOM_TRAK: 'trak',
    ATOM_TKHD: 'tkhd',
    ATOM_MDIA: 'mdia',
    ATOM_MDHD: 'mdhd',
    ATOM_MINF: 'minf',
    ATOM_HDLR: 'hdlr',
    ATOM_VMHD: 'vmhd',
    ATOM_SMHD: 'smhd',
    ATOM_STBL: 'stbl',
    ATOM_STSZ: 'stsz',
    ATOM_STCO: 'stco',
    ATOM_STSS: 'stss',
    ATOM_STTS: 'stts',
    ATOM_STSC: 'stsc',
    ATOM_CO64: 'co64',
    ATOM_STSD: 'stsd',
    ATOM_CTTS: 'ctts',
    ATOM_AVC1: 'avc1',
    ATOM_AVCC: 'avcC',
    ATOM_HEV1: 'hev1',
    ATOM_HVC1: 'hvc1',
    ATOM_HVCC: 'hvcC',
    ATOM_MP4A: 'mp4a',
    ATOM_ESDS: 'esds',
    ATOM_MDAT: 'mdat',
    ATOM_FTYP: 'ftyp',

    TRACK_TYPE_VIDEO: 'vide',
    TRACK_TYPE_AUDIO: 'soun',

    COMPONENT_NAME_VIDEO: 'VideoHandler',
    COMPONENT_NAME_AUDIO: 'SoundHandler',

    COMPRESSOR_NAME: 'NodeVideoLibrary', // should be exactly 16 symbols

    createAtom: function createAtom(type) {
        const AtomClasses = {
            'avc1': require('./atoms/atom-avc1'),
            'co64': require('./atoms/atom-co64'),
            'ctts': require('./atoms/atom-ctts'),
            'esds': require('./atoms/atom-esds'),
            'ftyp': require('./atoms/atom-ftyp'),
            'hdlr': require('./atoms/atom-hdlr'),
            'hev1': require('./atoms/atom-hev1'),
            'hvc1': require('./atoms/atom-hvc1'),
            'mdhd': require('./atoms/atom-mdhd'),
            'mdia': require('./atoms/atom-mdia'),
            'minf': require('./atoms/atom-minf'),
            'moov': require('./atoms/atom-moov'),
            'mp4a': require('./atoms/atom-mp4a'),
            'mvhd': require('./atoms/atom-mvhd'),
            'smhd': require('./atoms/atom-smhd'),
            'stbl': require('./atoms/atom-stbl'),
            'stco': require('./atoms/atom-stco'),
            'stsc': require('./atoms/atom-stsc'),
            'stsd': require('./atoms/atom-stsd'),
            'stss': require('./atoms/atom-stss'),
            'stsz': require('./atoms/atom-stsz'),
            'stts': require('./atoms/atom-stts'),
            'tkhd': require('./atoms/atom-tkhd'),
            'trak': require('./atoms/atom-trak'),
            'vmhd': require('./atoms/atom-vmhd'),
        }
        return new AtomClasses[type]();
    },
};
